### PR TITLE
Handle exception during shutdown

### LINKED ISSUE #91: 'QueueLengthSnapshotting' occasionally throws on shutdown
I occasionally see the following exception in the log file. Seems that some task cancellation isn't handled gracefully.

```
2017-12-12 21:31:55.2739|8|Warn|NServiceBus.Features.FeatureStartupTaskController|Exception occurred during stopping of feature startup task 'QueueLengthSnapshotting'.
System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at ServiceControl.Monitoring.QueueLength.QueueLengthSnapshotting.<<OnStart>b__2_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NServiceBus.Features.FeatureStartupTaskController.<Stop>d__5.MoveNext()
```

### PR DESCRIPTION
**Pull request by mikeminutillo**
Fixes #91

### CODE REVIEW

File: src/ServiceControl.Monitoring/QueueLength/QueueLength.cs [hunk 1]
```diff
@@ -31,7 +31,14 @@ protected override Task OnStart(IMessageSession session)
...
                     store.SnapshotCurrentQueueLengthEstimations(DateTime.UtcNow);
 
-                    await Task.Delay(snapshotInterval, stopTokenSource.Token);
+                    try
+                    {
+                        await Task.Delay(snapshotInterval, stopTokenSource.Token);
+                    }
+                    catch (TaskCanceledException)
+                    {
+                        // It's OK. It's quitting time
```
Comment (ramonsmits) [inline src/ServiceControl.Monitoring/QueueLength/QueueLength.cs]: Maybe instead do a 

    catch (TaskCanceledException) when (stopTokenSource.IsCancellationRequested)
